# 运动学配置
# 定义运动学求解器

/**:
  ros__parameters:
    my_arm_manipulator:
      kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
      kinematics_solver_search_resolution: 0.005
      kinematics_solver_timeout: 0.005
      kinematics_solver_attempts: 3
